### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isVisible' of null

### ISSUE THREAD

**Issue by AlexPasternak** [sfaedo/auto-reveal-active-file#3]
[Enter steps to reproduce below:]
1. Opened app and closed initial config window
2. Observe error, likely b/c app was launched with tree view hidden

**Atom Version**: 1.6.0
**System**: Mac OS X 10.10.5
**Thrown From**: [auto-reveal-active-file](https://github.com/sfaedo/auto-reveal-active-file) package, v0.3.1
### Stack Trace

Uncaught TypeError: Cannot read property 'isVisible' of null

```
At /Users/alexander.pasternak/.atom/packages/auto-reveal-active-file/lib/auto-reveal-active-file.js:13

TypeError: Cannot read property 'isVisible' of null
    at /Users/alexander.pasternak/.atom/packages/auto-reveal-active-file/lib/auto-reveal-active-file.js:13:61
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:255:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:336:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:592:19)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-writer"
    ],
    "themes": [
      "one-dark-ui",
      "monokai-seti"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-grails, v0.1.0
auto-reveal-active-file, v0.3.1
autoclose-html, v0.23.0
build-gradle, v0.6.0
file-bookmark, v0.3.1
highlight-selected, v0.11.2
language-gradle, v0.0.3
language-groovy, v0.6.0
linter, v1.11.3
linter-javac, v1.8.1
markdown-deluxe, v1.0.0
markdown-scroll-sync, v2.1.2
minimap, v4.21.0
minimap-highlight-selected, v4.4.0
monokai-seti, v0.7.0
open-recent, v5.0.0
pigments, v0.24.5

# Dev
No dev packages
```

**Comment by laughedelic** [comment]
Same thing here. Happens when I do `git commit`, it opens a new Atom window with the message and sometimes there are some tabs with other old messages, when I try to close them, I get this error.
